name: amount
description: Amount helps to convert numerical amount to words.
version: 1.0.0
homepage: https://github.com/justkawal/amount.git

environment:
  sdk: '>=2.8.1 <3.0.0'

#dependencies:

#dev_dependencies:
  #pedantic: ^1.9.0
